"""PRATYAKSA simulator routes.

Pratyaksa is **simulation-only**: every response is generated by the internal
deterministic simulator (``app.pratyaksa.simulator``).  There is no external ML
API proxy, no mode switching, and no reachability polling.
"""

from __future__ import annotations

from fastapi import APIRouter, Depends, Request
from fastapi.responses import JSONResponse

from app.core.errors import BadRequestError
from app.pratyaksa import simulator
from app.pratyaksa.state import SharedPratyaksaState, now_epoch
from app.schemas.pratyaksa import ModeSwitchRequest, PredictRequest

router = APIRouter(prefix="/pratyaksa", tags=["pratyaksa"])


def _get_state(request: Request) -> SharedPratyaksaState:
    return request.app.state.pratyaksa


async def _current_fleet(state: SharedPratyaksaState) -> tuple[list, float]:
    """Regenerate the deterministic fleet snapshot and return (fleet, epoch).

    The simulator is seeded per 5-minute time bucket, so regenerating on read
    keeps the data fresh (never a stale startup snapshot) at negligible cost.
    """
    fleet = simulator.generate_fleet()
    epoch = now_epoch()
    await state.update(fleet_data=fleet, generated_at=epoch)
    return fleet, epoch


@router.get("/status")
async def get_status(state: SharedPratyaksaState = Depends(_get_state)) -> dict:
    s = await state.read()
    fleet, epoch = await _current_fleet(state)
    return {
        "status": "success",
        "data": {
            "mode": s.mode.value,
            "fleet_count": len(fleet),
            "generated_at": _ago(epoch),
        },
    }


@router.get("/fleet")
async def get_fleet(state: SharedPratyaksaState = Depends(_get_state)) -> dict:
    s = await state.read()
    fleet, _ = await _current_fleet(state)
    return {
        "status": "success",
        "data": {
            "mode": s.mode.value,
            "fleet": [a.model_dump() for a in fleet],
            "total": len(fleet),
        },
    }


@router.get("/fleet/health")
async def get_fleet_health(state: SharedPratyaksaState = Depends(_get_state)) -> dict:
    s = await state.read()
    fleet, _ = await _current_fleet(state)
    normal = warning = critical = 0
    for asset in fleet:
        if asset.risk_level == "NORMAL":
            normal += 1
        elif asset.risk_level == "WARNING":
            warning += 1
        elif asset.risk_level == "CRITICAL":
            critical += 1
    avg_rul = 0.0
    if fleet:
        avg_rul = round(sum(a.lstm_rul_hours for a in fleet) / len(fleet) * 10.0) / 10.0

    return {
        "status": "success",
        "data": {
            "mode": s.mode.value,
            "total": len(fleet),
            "normal": normal,
            "warning": warning,
            "critical": critical,
            "avg_rul_hours": avg_rul,
        },
    }


@router.get("/result/{asset_id}")
async def get_result(asset_id: str) -> JSONResponse:
    return JSONResponse(
        {"status": "success", "mode": "simulasi", "data": simulator.generate_result(asset_id)}
    )


@router.post("/predict")
async def post_predict(body: PredictRequest) -> JSONResponse:
    if len(body.features) != 37:
        return JSONResponse(
            status_code=400,
            content={
                "status": "error",
                "message": f"features[] harus berisi tepat 37 angka, tapi menerima {len(body.features)}",
                "expected": 37,
                "received": len(body.features),
            },
        )
    return JSONResponse(
        {"status": "success", "mode": "simulasi", "data": simulator.generate_predict(body).model_dump()}
    )


@router.post("/workorder")
async def post_workorder(component: str, risk_score: float) -> JSONResponse:
    allowed_components = ["brake", "hydraulic", "engine", "transmission"]
    if component not in allowed_components:
        raise BadRequestError(f"component harus: {allowed_components}")
    if not (0.0 <= risk_score <= 1.0):
        raise BadRequestError("risk_score harus 0.0 - 1.0")

    return JSONResponse(
        {
            "status": "success",
            "mode": "simulasi",
            "data": simulator.generate_workorder(component, risk_score).model_dump(),
        }
    )


@router.get("/features")
async def get_features() -> JSONResponse:
    return JSONResponse(
        {"status": "success", "mode": "simulasi", "data": simulator.generate_features()}
    )


@router.post("/reload-models")
async def post_reload_models() -> JSONResponse:
    return JSONResponse(
        {
            "status": "success",
            "mode": "simulasi",
            "data": simulator.generate_reload_models().model_dump(),
        }
    )


@router.get("/explain/{prediction_id}")
async def get_explain(prediction_id: str) -> JSONResponse:
    return JSONResponse(
        {"status": "success", "mode": "simulasi", "data": simulator.generate_explain()}
    )


@router.post("/mode")
async def mode_switch(body: ModeSwitchRequest | None = None) -> JSONResponse:
    """Pratyaksa is simulation-only; the mode is always ``simulasi``."""
    return JSONResponse(
        {
            "status": "success",
            "message": "Pratyaksa berjalan dalam mode SIMULASI (satu-satunya mode).",
            "data": {"mode": "simulasi"},
        }
    )


def _ago(ts: float | None) -> str | None:
    if ts is None:
        return None
    from datetime import datetime, timezone

    elapsed = int(datetime.now(timezone.utc).timestamp() - ts)
    return f"{elapsed}s ago"
